# Generated by Django 4.2.2 on 2023-06-18 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_name_customuser_role_customuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
    ]
